app:
  replicaCount: 1
  image:
    repository: oldmanharry007/django-app
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: NodePort
    port: 8000
    nodePort: 30080

  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

postgres:
  image:
    repository: postgres
    tag: "13-alpine"
  
  service:
    port: 5432

  persistence:
    enabled: false