name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # 

jobs:
  build:
    #  на нашем srv сервере
    runs-on: self-hosted

    steps:
      # Шаг 1: Клонируем код на srv
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Извлекаем чистый номер 
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Шаг 3: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 4: Собираем и пушим Docker-образ на srv
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: oldmanharry007/django-app:${{ env.VERSION }}